# Generated by Django 4.0.5 on 2022-06-14 13:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MLDatasetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('version', models.CharField(max_length=200)),
                ('ml_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifacts.mldataset')),
            ],
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MLModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('version', models.CharField(max_length=200)),
                ('ml_dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifacts.mldatasetversion')),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifacts.mlmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Artifacts',
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='tags',
            field=models.ManyToManyField(to='artifacts.tag'),
        ),
    ]
